version: "3.9"

services:
  sbi-salesadvisor:
    build:
      context: .
      dockerfile: Dockerfile
    image: sbi-salesadvisor-v3:latest
    container_name: sbi-salesadvisor-v3
    ports:
      - "9494:9494"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: sbi-salesadvisor:latest
    container_name: sbi-salesadvisor
    ports:
      - "9494:9494"
    restart: unless-stopped